LogFile /var/log/clamav/clamd.log
LogTime
LogVerbose
DatabaseDirectory /var/lib/clamav
TCPSocket 3310
TCPAddr 0.0.0.0
MaxThreads 50
MaxConnectionQueueLength 30
ReadTimeout 180
User clamav
ScanMail
ScanArchive
ArchiveMaxCompressionRatio 300
