services:
  django:
    container_name: django
    build: .
    command: >
      sh -c "
             python3 manage.py migrate &&
             gunicorn GameJamSite.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000"
    volumes:
      - .:/app

      - "C:\\Users\\zilbe\\Desktop\\GJS_dir\\GJS\\docs\\source:/app/docs/source"
      - "C:\\Users\\zilbe\\Desktop\\GJS_dir\\GJS\\docs\\build:/app/docs/build"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    container_name: postgres
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A GameJamSite worker -l INFO
    environment:
      - HOME=/app
    volumes:
      - .:/app
    user: "1000:1000"
    depends_on:
      - django
      - redis
      - db

  celery-beat:
    container_name: celery-beat
    build:
      context: .
    command: celery -A GameJamSite beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - django
      - redis
      - db

  clamav:
    image: clamav/clamav:latest
    container_name: clamav
    restart: always
    ports:
      - "3310:3310"
    environment:
      - CLAMAV_NO_FRESHCLAMD=false
    volumes:
      - clamav_db:/var/lib/clamav
      #- ./clamav.conf:/etc/clamav/clamd.conf:ro
    command: >
      sh -c "
        echo 'TCPSocket 3310' >> /etc/clamav/clamd.conf &&
        echo 'TCPAddr 0.0.0.0' >> /etc/clamav/clamd.conf &&
        freshclam --foreground --quiet &
        sleep 10 &&
        exec clamd --foreground
      "
    healthcheck:
      test: ["CMD", "clamdscan", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s

volumes:
  postgres_data:
  clamav_db:
