# Generated by Django 5.1.1 on 2024-11-15 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam_polls', '0002_chosentheme_jam_uuid'),
        ('jams', '0007_uploadfile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chosentheme',
            old_name='jam_uuid',
            new_name='uuid',
        ),
        migrations.AddField(
            model_name='question',
            name='uuid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jams.gamejams'),
            preserve_default=False,
        ),
    ]
