# Generated by Django 5.1.1 on 2024-11-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam_polls', '0003_rename_jam_uuid_chosentheme_uuid_question_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
