# Generated by Django 5.1.1 on 2024-11-17 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jam_polls', '0004_alter_question_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='uuid',
            new_name='jam_uuid',
        ),
    ]
