# Generated by Django 5.1.1 on 2024-12-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jam_polls', '0005_rename_uuid_question_jam_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChosenTheme',
        ),
    ]
