# Generated by Django 5.1.6 on 2025-03-22 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam_polls', '0007_gamejamtheme_themevote_delete_question'),
        ('jams', '0013_alter_gamejam_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255, verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.AlterField(
            model_name='gamejamtheme',
            name='gamejam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jams.gamejam', verbose_name='Джем'),
        ),
        migrations.AlterField(
            model_name='gamejamtheme',
            name='theme',
            field=models.CharField(max_length=255, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='themevote',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jam_polls.gamejamtheme', verbose_name='Тема джема'),
        ),
        migrations.AlterField(
            model_name='themevote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
