# Generated by Django 5.1.1 on 2024-10-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameJams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_start', models.DateTimeField(verbose_name='start jam')),
                ('date_end', models.DateTimeField(verbose_name='end jam')),
                ('theme', models.TextField()),
                ('jam_slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
    ]
