# Generated by Django 5.1.1 on 2024-10-10 10:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0003_gamejams_id_alter_gamejams_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamejams',
            name='id',
        ),
        migrations.AlterField(
            model_name='gamejams',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
