# Generated by Django 5.1.1 on 2024-10-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0004_remove_gamejams_id_alter_gamejams_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='zip_uploads/')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='gamejams',
            name='status',
            field=models.CharField(choices=[('FN', 'Завершён'), ('OG', 'Идёт'), ('PR', 'Подготовка')], default='', max_length=3),
            preserve_default=False,
        ),
    ]
