# Generated by Django 5.1.1 on 2024-11-29 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0007_uploadfile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingUserJam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(blank=True)),
                ('jam_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jams.gamejams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_user', to=settings.AUTH_USER_MODEL)),
                ('user_who_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_rate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
