# Generated by Django 5.1.6 on 2025-03-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0008_ratinguserjam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamejams',
            name='date_end',
            field=models.DateTimeField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='gamejams',
            name='date_start',
            field=models.DateTimeField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='gamejams',
            name='status',
            field=models.CharField(choices=[('FN', 'Завершён'), ('OG', 'Идёт'), ('PR', 'Подготовка')], max_length=3, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='gamejams',
            name='theme',
            field=models.CharField(max_length=255, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='gamejams',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название джема'),
        ),
    ]
