# Generated by Django 5.1.6 on 2025-03-17 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0009_alter_gamejams_date_end_alter_gamejams_date_start_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratinguserjam',
            options={'verbose_name': 'Рейтинг джема', 'verbose_name_plural': 'Рейтинги джемов'},
        ),
        migrations.RenameField(
            model_name='uploadfile',
            old_name='file',
            new_name='game_file',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание игры'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/', verbose_name='Изображение игры'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='title',
            field=models.CharField(default='test game', max_length=100, verbose_name='Название игры'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamejams',
            name='status',
            field=models.CharField(choices=[('FN', 'Завершён'), ('OG', 'Идёт'), ('PR', 'Подготовка')], default='PR', max_length=3, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='gamejams',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='jam_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='jams.gamejams'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='uploaded_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
