# Generated by Django 5.1.6 on 2025-03-17 19:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jam_polls', '0006_delete_chosentheme'),
        ('jams', '0010_alter_ratinguserjam_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFile',
            new_name='Game',
        ),
        migrations.RenameModel(
            old_name='GameJams',
            new_name='GameJam',
        ),
    ]
