# Generated by Django 5.1.6 on 2025-03-18 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0011_rename_uploadfile_game_rename_gamejams_gamejam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='gamejam',
            options={'verbose_name': 'Геймджем', 'verbose_name_plural': 'Геймджемы'},
        ),
        migrations.AlterField(
            model_name='game',
            name='game_file',
            field=models.FileField(upload_to='zip_uploads/', verbose_name='Файл игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='jam_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='jams.gamejam', verbose_name='Джем'),
        ),
        migrations.AlterField(
            model_name='gamejam',
            name='theme',
            field=models.CharField(default='', max_length=255, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='gamejam',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='gamejam',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_winner', to=settings.AUTH_USER_MODEL, verbose_name='Победитель'),
        ),
        migrations.AlterField(
            model_name='ratinguserjam',
            name='jam_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jams.gamejam', verbose_name='Джем'),
        ),
        migrations.AlterField(
            model_name='ratinguserjam',
            name='stars',
            field=models.IntegerField(blank=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='ratinguserjam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='ratinguserjam',
            name='user_who_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_rate', to=settings.AUTH_USER_MODEL, verbose_name='Кто оценил'),
        ),
    ]
