# Generated by Django 5.1.6 on 2025-03-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0012_alter_game_options_alter_gamejam_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamejam',
            name='theme',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тема'),
        ),
    ]
