# Generated by Django 5.1.6 on 2025-04-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0013_alter_gamejam_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
