# Generated by Django 5.1.6 on 2025-06-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0015_alter_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamejam',
            name='date_rating',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оценки'),
        ),
        migrations.AddField(
            model_name='gamejam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jams/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='gamejam',
            name='status',
            field=models.CharField(choices=[('FN', 'Завершён'), ('RT', 'Оценивание'), ('OG', 'Идёт'), ('PR', 'Подготовка')], default='PR', max_length=3, verbose_name='Статус'),
        ),
    ]
