# Generated by Django 5.1.6 on 2025-10-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0016_gamejam_date_rating_gamejam_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamejam',
            name='date_rating',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оценивания'),
        ),
        migrations.AlterField(
            model_name='gamejam',
            name='status',
            field=models.CharField(choices=[('FN', 'Завершён'), ('OG', 'Идёт'), ('RT', 'Оценка'), ('PR', 'Подготовка')], default='PR', max_length=3, verbose_name='Статус'),
        ),
    ]
