# Generated by Django 5.1.6 on 2026-02-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0017_alter_gamejam_date_rating_alter_gamejam_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='jam_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='jams.gamejam', verbose_name='Джем'),
        ),
    ]
