# Generated by Django 5.1.6 on 2026-02-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0018_alter_game_jam_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamejam',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Описание джема'),
        ),
    ]
