# Generated by Django 5.1.6 on 2026-03-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0019_gamejam_description'),
        ('users', '0014_alter_team_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamejam',
            name='has_poll',
            field=models.BooleanField(default=True, verbose_name='Есть голосование'),
        ),
        migrations.AddField(
            model_name='gamejam',
            name='teams',
            field=models.ManyToManyField(blank=True, to='users.team', verbose_name='Команды участиники'),
        ),
    ]
