# Generated by Django 5.1.6 on 2026-03-27 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0020_gamejam_has_poll_gamejam_teams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamejam',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jam_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор геймджема'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamejam',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание джема'),
        ),
        migrations.AlterField(
            model_name='gamejam',
            name='has_poll',
            field=models.BooleanField(default=False, verbose_name='Есть голосование'),
        ),
    ]
