# Generated by Django 5.1.6 on 2026-04-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0021_gamejam_author_alter_gamejam_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratinguserjam',
            name='title',
            field=models.CharField(default='Общая оценка', max_length=255, verbose_name='Категория оценки'),
        ),
    ]
