# Generated by Django 5.1.6 on 2026-04-04 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0022_ratinguserjam_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Общая оценка', max_length=255, verbose_name='Категория оценки')),
                ('jam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jams.gamejam', verbose_name='Джем')),
            ],
        ),
    ]
