# Generated by Django 5.1.6 on 2026-04-04 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0023_ratingcriterion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratinguserjam',
            name='criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criteria', to='jams.ratingcriterion', verbose_name='Критерии оценки'),
        ),
    ]
