# Generated by Django 5.1.6 on 2026-04-18 08:27

import django_clamd.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0024_ratinguserjam_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_file',
            field=models.FileField(upload_to='zip_uploads/', validators=[django_clamd.validators.validate_file_infection], verbose_name='Файл игры'),
        ),
    ]
