# Generated by Django 5.1.1 on 2024-10-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='zip_uploads/')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
