# Generated by Django 5.1.1 on 2024-11-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_uploadfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
