# Generated by Django 5.1.6 on 2025-03-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_image',
            field=models.ImageField(null=True, upload_to='users'),
        ),
        migrations.AddField(
            model_name='user',
            name='hat_image',
            field=models.ImageField(null=True, upload_to='users'),
        ),
    ]
