# Generated by Django 5.1.6 on 2025-03-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar_image_user_hat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hat_image',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
