# Generated by Django 5.1.6 on 2025-06-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avatar_image_alter_user_hat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hat_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users'),
        ),
    ]
