# Generated by Django 5.1.6 on 2025-10-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_avatar_image_alter_user_hat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribers',
            field=models.IntegerField(default=0, verbose_name='Подписчики'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hat_image',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
