# Generated by Django 5.1.6 on 2025-10-08 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_follower_delete_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='Подписчики', to=settings.AUTH_USER_MODEL),
        ),
    ]
