# Generated by Django 5.1.6 on 2025-10-08 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_subscribers_user_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
