# Generated by Django 5.1.6 on 2026-03-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_team_created_at_team_created_by_team_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
    ]
