# Generated by Django 5.1.6 on 2026-04-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_teammembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
    ]
