# Generated by Django 5.1.6 on 2026-04-02 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='team_users', through='users.TeamMembership', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
