# Generated by Django 5.1.6 on 2026-04-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
